#pragma once

// GLFW mouse button codes
#define BLACK_MOUSE_BUTTON_1         0
#define BLACK_MOUSE_BUTTON_2         1
#define BLACK_MOUSE_BUTTON_3         2
#define BLACK_MOUSE_BUTTON_4         3
#define BLACK_MOUSE_BUTTON_5         4
#define BLACK_MOUSE_BUTTON_6         5
#define BLACK_MOUSE_BUTTON_7         6
#define BLACK_MOUSE_BUTTON_8         7
#define BLACK_MOUSE_BUTTON_LAST      BLACK_MOUSE_BUTTON_8
#define BLACK_MOUSE_BUTTON_LEFT      BLACK_MOUSE_BUTTON_1
#define BLACK_MOUSE_BUTTON_RIGHT     BLACK_MOUSE_BUTTON_2
#define BLACK_MOUSE_BUTTON_MIDDLE    BLACK_MOUSE_BUTTON_3